frontend/controllers/RegulasiController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\master\Regulasi;
use frontend\models\master\RegulasiSearch;

/**
 * Regulasi Controller, controller ini hanya menampilkan data Regulasi Perizinan
 */
class RegulasiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'view', 'download', 'preview-dok'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = '/dashboard/main';
        return parent::beforeAction($action);
    }

    /**
     * Lists all Regulasi models.
     * @param jenis_layanan_id
     * @return mixed
     */
    public function actionIndex($jenisLayananId)
    {
//        ActivityLog::insertLog("View", "", "Menampilkan Daftar Regulasi");
        $searchModel = new RegulasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['jenis_layanan_id' => $jenisLayananId]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'jenisLayananId' => $jenisLayananId
        ]);
    }

    /**
     * Displays a single Regulasi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Download dokumen regulasi.
     * @param integer $path
     * @return file
     */
    public function actionDownload($path, $file)
    {
        $path = (explode('/', $path));
        $result = array_slice($path, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        if (file_exists($fullpath)) {
            return Yii::$app->response->sendFile($fullpath);
        } else {
            return 'File Not Found';
        }
    }

    /**
     * Preview dokumen regulasi.
     * @param integer $path
     * @return file
     */
    public function actionPreviewDok($path, $file)
    {
        $array = (explode('/', $path));
        $result = array_slice($array, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        return $this->renderAjax('preview-dok', [
            'path' => $path,
            'file' => $file,
            'fullpath' => $fullpath,
        ]);
    }

    /**
     * Finds the Regulasi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Regulasi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Regulasi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\perusahaan\SkPerusahaanKendaraanSearch;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use frontend\modules\permohonan\models\PermohonanSearch;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\master\Kabupaten;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\perusahaan\Perusahaan;
use yii\helpers\Json;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // change layout for error action
            if ($action->id == 'error' && !Yii::$app->user->isGuest) $this->layout = 'dashboard/main';
            return true;
        } else {
            return false;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'maxLength' => 4,
                'minLength' => 4
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post()) && $model->sendEmail(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('success', 'Thank you for getting in touch!.');
            return $this->redirect(['site/index#contact']);
        }

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['dashboard']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['dashboard']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionDashboard()
    {
        $this->layout = 'dashboard/main';

        if (!Yii::$app->user->isGuest) {
            return $this->render('dashboard');
        } else {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        $listJenisBadanUsaha = \yii\helpers\ArrayHelper::map(\common\models\master\JenisBadanUsaha::find()->where(['is_delete' => 0])->all(), 'id', 'jenis_badan_usaha');
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Terima Kasih, silahkan buka email anda untuk mengetahui langkah selanjutnya.');
            return $this->refresh();
        }

        return $this->render('signup', [
            'model' => $model,
            'items' => $listJenisBadanUsaha,
        ]);
    }

    public function actionGetKabupaten()
    {
        if (Yii::$app->request->isAjax) {
            $provinsiId = Yii::$app->request->post('provinsi_id');
            $getKabupaten = Kabupaten::find()->where(['provinsi_id' => $provinsiId, 'is_active' => 1, 'is_delete' => 0])->all();
            return Json::encode($getKabupaten);
        }
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Terima Kasih, silahkan buka email anda untuk mengetahui langkah selanjutnya.');

                return $this->redirect(['request-password-reset']);
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionReportKendaraan()
    {
        $this->layout = 'dashboard/main';
        $searchModel = new SkPerusahaanKendaraanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->joinWith('sk')->andWhere(['t_sk_perusahaan.perusahaan_id' => Yii::$app->user->identity->perusahaan->id]);

        return $this->render('report-kendaraan', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionReportPermohonan()
    {
        $this->layout = 'dashboard/main';
        $searchModel = new PermohonanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['perusahaan_id' => Yii::$app->user->identity->perusahaan->id]);

        return $this->render('report-permohonan', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Password Baru Berhasil Disimpan.');

            return $this->redirect(['login']);
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail() !== NULL) {
            Yii::$app->session->setFlash('success', 'Terimakasih, Akun Anda Telah Terverifikasi!');
            return $this->redirect(['login']);
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Silahkan.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    /**
     * Error action.
     * @var $exception Error handler
     * @return string
     */
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;

frontend/views/layouts/dashboard/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;

//AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Html::csrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>

  <?php $baseTheme = Yii::$app->getUrlManager()->getBaseUrl().'/gentelella-master';?>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Bootstrap -->
  <link href="<?= $baseTheme;?>/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="<?= $baseTheme;?>/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <!-- NProgress -->
  <link href="<?= $baseTheme;?>/vendors/nprogress/nprogress.css" rel="stylesheet">
  <!-- Animate.css -->
  <link href="<?= $baseTheme;?>/vendors/animate.css/animate.min.css" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="<?= $baseTheme;?>/build/css/custom.min.css" rel="stylesheet">
  <?php $this->head() ?>


</head>
<body class="login">
<?php $this->beginBody() ?>
<div>
  <a class="hiddenanchor" id="signup"></a>
  <a class="hiddenanchor" id="signin"></a>

  <div class="login_wrapper">

    <?= $content ;?>

  </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/dashboard/main.php
<!-- Header -->
<?php include_once('tpl_header.php')?>

<!-- Side Left -->
<?php include_once('tpl_left.php')?>

<!-- Side Left -->
<?php include_once('tpl_top.php')?>

<!-- Side Right -->
<?php include_once('tpl_right.php')?>

<!-- Footer -->
<?php include_once('tpl_footer.php')?>

frontend/views/layouts/dashboard/tpl_footer.php
  <!-- footer content -->
  <footer>
    <div class="pull-right">
      SPIONJABAR</a>
    </div>
    <div class="clearfix"></div>
  </footer>
  <!-- /footer content -->

  </div>
</div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/dashboard/tpl_header.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use frontend\assets\AppAsset;
use yii\helpers\Html;

AppAsset::register($this);

$baseTheme = Yii::$app->getUrlManager()->getBaseUrl().'/gentelella-master/';

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta charset="<?= Yii::$app->charset ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="<?= $baseTheme;?>favicon.ico" type="image/x-icon">
  <?= Html::csrfMetaTags() ?>
  <title><?= Yii::$app->name.' | '.Html::encode($this->title) ?></title>

  <?php $baseTheme = Yii::$app->getUrlManager()->getBaseUrl().'/gentelella-master';?>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <?php $this->head() ?>


</head>
<body class="nav-md">
<?php $this->beginBody() ?>
<div class="container body">
  <div class="main_container">

frontend/views/layouts/dashboard/tpl_left.php
<?php

use yii\helpers\Url;
use common\models\User;
use common\models\UserRole;
use common\models\master\JenisLayanan;
use common\models\master\JenisPerizinan;

?>

<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">

            <a href="<?= Url::toRoute('/site/dashboard'); ?>" class="site_title">
                <img src="<?= Yii::$app->getUrlManager()->getBaseUrl() . '/frontend/images/logo.png' ?>" width="90%;"
                     align="center" alt="">
            </a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="<?= $baseTheme; ?>/images/avatar.png" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2 style="word-wrap: break-word;"><?php if (!Yii::$app->user->isGuest) {
                        echo ucwords(Yii::$app->user->identity->perusahaan->nama_perusahaan);
                    } ?></h2>
                <p><?php if (!Yii::$app->user->isGuest) {
                        echo ucwords(UserRole::findOne(User::findOne(Yii::$app->user->identity->id)->user_role_id)->role);
                    } ?></p>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Main Menu</h3>
                <ul class="nav side-menu">
                    <li><a href="<?= Url::toRoute('/site/dashboard'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a>
                    </li>
                </ul>

                <ul class="nav side-menu">
                    <li><a href="<?= Url::toRoute('/perusahaan/profil-perusahaan'); ?>"><i class="fa fa-building"></i>
                            Profil Perusahaan</a></li>
                </ul>

                <ul class="nav side-menu">
                    <li class="<?= Yii::$app->controller->id == "regulasi" ? 'active' : ''; ?>"><a><i
                                    class="fa fa-balance-scale"></i> Informasi Regulasi <span
                                    class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu"
                            style="<?= Yii::$app->controller->id == "regulasi" ? 'display: block;' : 'display: none;'; ?>">
                            <?php foreach (JenisLayanan::find()->where(['is_delete' => 0, 'is_active' => 1])->all() as $key => $value) : ?>
                                <li>
                                    <a href="<?= Url::toRoute(['/regulasi/index', 'jenisLayananId' => $value->id]); ?>"><?= $value->jenis_layanan ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                </ul>
                <?php if (Yii::$app->user->identity->perusahaan->is_verified == 2) : ?>
                    <ul class="nav side-menu">
                        <?php foreach (JenisLayanan::find()->where(['is_active' => 1, 'is_delete' => 0])->all() as $index => $data) : ?>
                            <li><a><i class="fa fa-file"></i> <?= $data->jenis_layanan ?> <span
                                            class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <?php foreach ($data->jenisAngkutan as $indexAngkutan => $dataAngkutan) : ?>
                                        <li <?= (Yii::$app->request->get('jenis_angkutan_id') == $dataAngkutan->id) ? "class='active '" : '' ?>>
                                            <a href="<?= Url::toRoute(['/permohonan/permohonan/index', 'jenis_angkutan_id' => $dataAngkutan->id]) ?>"><?= $dataAngkutan->jenis_angkutan ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        <?php endforeach; ?>
                    </ul>

                    <ul class="nav side-menu">
                        <li><a><i class="fa fa-book"></i> Laporan <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li><a href="<?= Url::toRoute('/site/report-permohonan'); ?>"> Data Perijinan</a></li>
                                <li><a href="<?= Url::toRoute('/site/report-kendaraan'); ?>"> Data Kendaraan</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav side-menu">
                        <li><a href="<?= Url::toRoute('/permohonan/permohonan/undangan'); ?>"><i
                                        class="fa fa-mail-reply"></i>
                                Undangan</a></li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <!-- /sidebar menu -->
</div>

frontend/views/layouts/dashboard/tpl_right.php
<!-- page content -->
<div class="right_col" role="main">
    <?php if ($this->title != 'Dashboard') { ?>
        <div class="page-title">
            <div class="title_left">
                <h3><?= $this->title; ?></h3>
            </div>

            <div class="title_right">
                <?= yii\widgets\Breadcrumbs::widget(['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],]) ?>
            </div>
        </div>
    <?php } ?>

    <div class="clearfix"></div>

    <div class="row">
        <div class="container">
            <?= common\widgets\Alert::widget() ?>
            <?= $content; ?>
        </div>
    </div>
    <?= yii\helpers\Html::beginForm(['/site/logout'], 'post', ['id' => 'logout-form']); ?>
    <?= yii\helpers\Html::endForm(); ?>
</div>
<!-- /page content -->

frontend/views/layouts/dashboard/tpl_top.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="javascript:document.getElementById('logout-form').submit()">
                        <i class="fa fa-sign-out"></i> Log Out</a>
                </li>

                <li>
                    <a href="<?= yii\helpers\Url::to(['../frontend/site/index']); ?>"
                       class="dropdown-toggle info-number" target="_blank">
                        <i class="fa fa-globe"></i> Frontend
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->