backend/modules/approval/controllers/PerusahaanDokumenController.php
<?php

namespace backend\modules\approval\controllers;

use Yii;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\perusahaan\PerusahaanDokumen;
use common\models\perusahaan\Perusahaan;
use common\models\master\JenisDokumenPerusahaan;
use common\models\master\JenisDokumenPerusahaanSearch;
use common\models\ActivityLog;
use yii\web\NotFoundHttpException;

class PerusahaanDokumenController extends \yii\web\Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['view', 'preview-dok', 'download'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Download dokumen regulasi.
     * @param integer $path
     * @return file
     */
    public function actionDownload($path, $file)
    {
        $path = (explode('/', $path));
        $result = array_slice($path, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        if (file_exists($fullpath)) {
            return Yii::$app->response->sendFile($fullpath);
        } else {
            return 'File Not Found';
        }
    }

    /**
     * Preview dokumen.
     * @param integer $path
     * @return file
     */
    public function actionPreviewDok($path, $file)
    {
        $array = (explode('/', $path));
        $result = array_slice($array, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        return $this->renderAjax('preview-dok', [
            'path' => $path,
            'file' => $file,
            'fullpath' => $fullpath,
        ]);
    }

    /**
     * Finds the PagesData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PagesData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PerusahaanDokumen::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/modules/approval/views/perusahaan-dokumen/preview-dok.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
?>
<?php if (file_exists($fullpath)): ?>
  <?= \yii2assets\pdfjs\PdfJs::widget([
    'url'=> Url::toRoute(['perusahaan-dokumen/download', 'path' => $path, 'file' => $file]),
    'buttons'=>[
      'presentationMode' => false,
      'openFile' => false,
      'print' => true,
      'download' => true,
      'viewBookmark' => false,
      'secondaryToolbarToggle' => false
    ]
  ]); ?>
<?php else: ?>
  <h2>File not found</h2>
<?php endif; ?>

backend/modules/approval/views/perusahaan-dokumen/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\models\User;
use yii\helpers\Url;
use common\components\Helper;
/* @var $this yii\web\View */
/* @var $model common\models\master\JenisLayanan */

$this->title = $model->nama_dokumen;
?>
<table class="table table-striped table-bordered">
    <tr>
        <th>Jenis Dokumen</th>
        <td><?= $model->jenisDokumen->jenis_dokumen ?></td>
    </tr>
    <tr>
        <th>Nama Dokumen</th>
        <td><?= $model->nama_dokumen ?></td>
    </tr>
    <tr>
        <th>No Dokumen</th>
        <td><?= $model->no_dokumen ?></td>
    </tr>

    <?php if($model->jenis_dokumen_perusahaan_id == 3 || $model->jenis_dokumen_perusahaan_id == 5 || $model->jenis_dokumen_perusahaan_id == 7 || $model->jenis_dokumen_perusahaan_id == 8): ?>
        <tr>
            <th><?= $model->getLabelTgl($model->jenis_dokumen_perusahaan_id) ?></th>
            <td>
                <?php 
                    $today = Date('Y-m-d');
                    $label = "";

                    if($model->jenis_dokumen_perusahaan_id == 7){
                        if($model->tgl_dokumen == $today){
                            $label = "<span class='label label-danger' style='font-size: 10px;'>".Helper::getTanggalBiasa($model->tgl_dokumen)." | Expired</span>";
                        }else{
                            $label = "<span class='label label-success' style='font-size: 10px;'>".Helper::getTanggalBiasa($model->tgl_dokumen)."</span>";
                        }
                    }elseif($model->jenis_dokumen_perusahaan_id == 3 || $model->jenis_dokumen_perusahaan_id == 5 || $model->jenis_dokumen_perusahaan_id == 8){
                        $label = Helper::getTanggalBiasa($model->tgl_dokumen);
                    }

                    echo $label;
                ?>
            </td>
        </tr>
    <?php endif; ?>
    <tr>
        <th>Keterangan</th>
        <td><?= $model->keterangan ?></td>
    </tr>
</table>
<?= Html::button(' <i class="glyphicon glyphicon-remove"></i> Cancel', ['class' => 'btn btn-danger', 'data-dismiss' => 'modal']) ?>