backend/controllers/UserCategoryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\UserRole;
use backend\models\UserRoleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserCategoryController implements the CRUD actions for UserRole model.
 */
class UserCategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all UserRole models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserRoleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single UserRole model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new UserRole model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserRole();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing UserRole model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing UserRole model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();

        $model = $this->findModel($id);
        $model->is_delete = 1;

        if($model->save()){
            return $this->redirect(['index']);
        }
    }

    /**
     * Finds the UserRole model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserRole the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserRole::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;

use frontend\models\perusahaan\SkPerusahaanKendaraanSearch;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use frontend\modules\permohonan\models\PermohonanSearch;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\master\Kabupaten;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\perusahaan\Perusahaan;
use yii\helpers\Json;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // change layout for error action
            if ($action->id == 'error' && !Yii::$app->user->isGuest) $this->layout = 'dashboard/main';
            return true;
        } else {
            return false;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
                'maxLength' => 4,
                'minLength' => 4
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post()) && $model->sendEmail(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('success', 'Thank you for getting in touch!.');
            return $this->redirect(['site/index#contact']);
        }

        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['dashboard']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['dashboard']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionDashboard()
    {
        $this->layout = 'dashboard/main';

        if (!Yii::$app->user->isGuest) {
            return $this->render('dashboard');
        } else {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        $listJenisBadanUsaha = \yii\helpers\ArrayHelper::map(\common\models\master\JenisBadanUsaha::find()->where(['is_delete' => 0])->all(), 'id', 'jenis_badan_usaha');
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Terima Kasih, silahkan buka email anda untuk mengetahui langkah selanjutnya.');
            return $this->refresh();
        }

        return $this->render('signup', [
            'model' => $model,
            'items' => $listJenisBadanUsaha,
        ]);
    }

    public function actionGetKabupaten()
    {
        if (Yii::$app->request->isAjax) {
            $provinsiId = Yii::$app->request->post('provinsi_id');
            $getKabupaten = Kabupaten::find()->where(['provinsi_id' => $provinsiId, 'is_active' => 1, 'is_delete' => 0])->all();
            return Json::encode($getKabupaten);
        }
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Terima Kasih, silahkan buka email anda untuk mengetahui langkah selanjutnya.');

                return $this->redirect(['request-password-reset']);
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionReportKendaraan()
    {
        $this->layout = 'dashboard/main';
        $searchModel = new SkPerusahaanKendaraanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->joinWith('sk')->andWhere(['t_sk_perusahaan.perusahaan_id' => Yii::$app->user->identity->perusahaan->id]);

        return $this->render('report-kendaraan', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionReportPermohonan()
    {
        $this->layout = 'dashboard/main';
        $searchModel = new PermohonanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andFilterWhere(['perusahaan_id' => Yii::$app->user->identity->perusahaan->id]);

        return $this->render('report-permohonan', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Password Baru Berhasil Disimpan.');

            return $this->redirect(['login']);
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail() !== NULL) {
            Yii::$app->session->setFlash('success', 'Terimakasih, Akun Anda Telah Terverifikasi!');
            return $this->redirect(['login']);
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Silahkan.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    /**
     * Error action.
     * @var $exception Error handler
     * @return string
     */
    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;

backend/views/layoutsbak/_menu_administrator.php
<?php

use yii\helpers\Url;
use common\models\master\JenisLayanan;
?>

<div class="menu_section">
  <h3>Main Menu</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/site/index'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
    <li class="<?= Yii::$app->controller->id == "regulasi" ? 'active' : ''; ?>"><a><i class="fa fa-balance-scale"></i> Regulasi <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu" style="<?= Yii::$app->controller->id == "regulasi" ? 'display: block;' : 'display: none;'; ?>">
        <?php foreach (JenisLayanan::find()->where(['is_delete' => 0, 'is_active' => 1])->all() as $key => $value) : ?>
          <li><a href="<?= Url::toRoute(['/perusahaan/regulasi', 'jenisLayananId' => $value->id]); ?>"><?= $value->jenis_layanan ?></a></li>
        <?php endforeach; ?>
      </ul>
    </li>
    <li class="<?php if (Yii::$app->controller->id == 'perusahaan') {
                  echo 'active';
                } ?>">
      <a><i class="fa fa-bank"></i> Perusahaan <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li class="<?php if (Yii::$app->controller->id == 'perusahaan') {
                      echo 'active';
                    } ?>"><a href="<?= Url::toRoute('/perusahaan/perusahaan'); ?>">Data Perusahaan</a></li>
      </ul>
    </li>

    <li><a><i class="fa fa-th"></i> Tracking Permohonan <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-ijin-prinsip/monitoring-index'); ?>">Ijin Prinsip</a></li>
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-info-kepengusahaan/monitoring-index'); ?>">Info Kepengusahaan</a></li>
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-permohonan-rekomendasi/monitoring-index'); ?>">Rekomendasi Realisasi Ijin Prinsip</a></li>
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-rekom-perpanjangan-sk/monitoring-index'); ?>">Rekomendasi Perpanjangan SK</a></li>
      </ul>
    </li>
    <li><a href="<?= Url::toRoute('/reporting/reporting/index'); ?>"><i class="fa fa-newspaper-o"></i> Reporting</a></li>

  </ul>
</div>


<div class="menu_section">
  <h3>System</h3>
  <ul class="nav side-menu">
    <li class="">
      <a><i class="fa fa-database"></i> Master <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li><a href="<?= Url::toRoute('/master/terminal'); ?>">Data Terminal</a></li>
        <li><a href="<?= Url::toRoute('/master/trayek'); ?>">Data Trayek</a></li>
        <li><a href="<?= Url::toRoute('/master/tipe-terminal'); ?>">Tipe Terminal</a></li>
        <li><a href="<?= Url::toRoute('/master/jenis-badan-usaha'); ?>">Jenis Badan Usaha</a></li>
        <li><a href="<?= Url::toRoute('/master/jenis-dokumen-perusahaan'); ?>">Jenis Dokumen Perusahaan</a></li>
        <li><a href="<?= Url::toRoute('/master/jenis-kendaraan'); ?>">Jenis Kendaraan</a></li>
        <li><a>Master Permohonan<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="<?= Url::toRoute('/master/jenis-layanan'); ?>">Jenis Layanan</a> </li>
            <li><a href="<?= Url::toRoute('/master/jenis-angkutan'); ?>">Jenis Angkutan</a> </li>
            <li><a href="<?= Url::toRoute('/master/jenis-permohonan'); ?>">Jenis Permohonan</a> </li>
            <li><a href="<?= Url::toRoute('/master/tipe-permohonan'); ?>">Tipe Permohonan</a> </li>
          </ul>
        </li>
        <li class="<?php if (
                      Yii::$app->controller->id == 'provinsi'  ||
                      Yii::$app->controller->id == 'kabupaten' ||
                      Yii::$app->controller->id == 'kecamatan' ||
                      Yii::$app->controller->id == 'kelurahan'
                    ) {
                      echo 'active';
                    } ?>">
          <a>Master Wilayah<span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu" style="<?php if (
                                              Yii::$app->controller->id == 'provinsi'  ||
                                              Yii::$app->controller->id == 'kabupaten' ||
                                              Yii::$app->controller->id == 'kecamatan' ||
                                              Yii::$app->controller->id == 'kelurahan'
                                            ) {
                                              echo 'display:block';
                                            } ?>">
            <li class="<?php if (Yii::$app->controller->id == 'provinsi') {
                          echo 'current-page';
                        } ?>">
              <a href="<?= Url::toRoute('/master/provinsi'); ?>">Provinsi</a>
            </li>
            <li class="<?php if (Yii::$app->controller->id == 'kabupaten') {
                          echo 'current-page';
                        } ?>">
              <a href="<?= Url::toRoute('/master/kabupaten'); ?>">Kabupaten/Kota</a>
            </li>
            <li class="<?php if (Yii::$app->controller->id == 'kecamatan') {
                          echo 'current-page';
                        } ?>">
              <a href="<?= Url::toRoute('/master/kecamatan'); ?>">Kecamatan</a>
            </li>
            <li class="<?php if (Yii::$app->controller->id == 'kelurahan') {
                          echo 'current-page';
                        } ?>">
              <a href="<?= Url::toRoute('/master/kelurahan'); ?>">Kelurahan/Desa</a>
            </li>
          </ul>
        </li>
      </ul>
    </li>

    <li><a><i class="fa fa-users"></i> Users <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li><a href="<?= Url::toRoute('user-management/index'); ?>">Users</a></li>
        <li><a href="<?= Url::toRoute('user-category/index'); ?>">User Role</a></li>
      </ul>
    </li>

    <li><a><i class="fa fa-cogs"></i> System Config <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li><a href="<?= Url::toRoute('activity-log/index'); ?>">User Log Activity</a></li>
      </ul>
    </li>
  </ul>
</div>

backend/views/layoutsbak/_menu_approval.php
<?php

use yii\helpers\Url;
use common\models\master\JenisLayanan;
?>

<div class="menu_section">
  <h3>Main Menu</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/site/index'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  </ul>
</div>
<?php if (Yii::$app->user->identity->user_role_id == 3) : ?>
  <div class="menu_section">
    <h3>Verifikasi Perusahaan</h3>
    <ul class="nav side-menu">
      <li><a href="<?= Url::toRoute(['/approval/perusahaan/index', 'jenis_perusahaan' => 2]); ?>"><i class="fa fa-archive"></i> Dok. Perusahaan Baru</a></li>
      <li><a href="<?= Url::toRoute(['/approval/perusahaan/index', 'jenis_perusahaan' => 1]); ?>"><i class="fa fa-archive"></i> Dok. Perusahaan Lama</a></li>
    </ul>
  </div>
<?php endif; ?>

<div class="menu_section">
<h3>Verifikasi Perusahaan</h3>
  <ul class="nav side-menu">
    <?php foreach (JenisLayanan::find()->where(['is_active' => 1, 'is_delete' => 0])->all() as $index => $data) : ?>
      <li><a><i class="fa fa-file"></i> <?= $data->jenis_layanan ?> <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <?php foreach ($data->jenisAngkutan as $indexAngkutan => $dataAngkutan) : ?>
            <li <?= (Yii::$app->request->get('jenis_angkutan_id') ==  $dataAngkutan->id) ? "class='active '" : '' ?>><a href="<?= Url::toRoute(['/permohonan/permohonan/index', 'jenis_angkutan_id' => $dataAngkutan->id]) ?>"><?= $dataAngkutan->jenis_angkutan ?></a></li>
          <?php endforeach; ?>
        </ul>
      </li>
    <?php endforeach; ?>
  </ul>

  <ul class="nav side-menu">
    <li><a><i class="fa fa-book"></i> Laporan <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <li><a href="<?= Url::toRoute('/site/report'); ?>"><i class="fa fa-book"></i> Status Perijinan</a></li>
        <li><a href="<?= Url::toRoute('/site/report'); ?>"><i class="fa fa-book"></i> Report</a></li>
      </ul>
    </li>
  </ul>
</div>

backend/views/layoutsbak/_menu_cetak.php
<?php

use yii\helpers\Url;
use common\models\master\JenisLayanan;
?>

<div class="menu_section">
  <h3>Main Menu</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/site/index'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  </ul>
</div>

<div class="menu_section">
  <h3>Cetak Permohonan</h3>
  <ul class="nav side-menu">
    <li><a><i class="fa fa-print"></i> Cetak Permohonan <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <!-- <li><a href="<?= Url::toRoute('/verifikator/verifikasi-ijin-prinsip/index'); ?>">Ijin Prinsip</a></li> -->
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-info-kepengusahaan/index'); ?>">Permohonan Ijin Prinsip</a></li>
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-permohonan-rekomendasi/index'); ?>">Info Realisasi</a></li>
        <!-- <li><a href="<?= Url::toRoute('/verifikator/verifikasi-rekom-perpanjangan-sk/index'); ?>">Rekomendasi Perpanjangan SK</a></li> -->
      </ul>
    </li>
    <li><a><i class="fa fa-check-square-o"></i> Upload Persetujuan <span class="fa fa-chevron-down"></span></a>
      <ul class="nav child_menu">
        <!-- <li><a href="<?= Url::toRoute('/verifikator/verifikasi-ijin-prinsip/monitoring-index'); ?>">Ijin Prinsip</a></li> -->
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-info-kepengusahaan/monitoring-index'); ?>">Permohonan Ijin Prinsip</a></li>
        <li><a href="<?= Url::toRoute('/verifikator/verifikasi-permohonan-rekomendasi/monitoring-index'); ?>">Info Realisasi</a></li>
        <!-- <li><a href="<?= Url::toRoute('/verifikator/verifikasi-rekom-perpanjangan-sk/monitoring-index'); ?>">Rekomendasi Perpanjangan SK</a></li> -->
      </ul>
    </li>
  </ul>
</div>

backend/views/layoutsbak/_menu_jr.php
<?php

use yii\helpers\Url;
use common\models\master\JenisLayanan;
?>

<div class="menu_section">
  <h3>Main Menu</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/site/index'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
  </ul>
</div>

<div class="menu_section">
  <h3>Cek IWKBU Permohonan</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/verifikator/verifikasi-ijin-prinsip/index'); ?>"><i class="fa fa-check-circle"></i> Ijin Prinsip</a></li>
    <li><a href="<?= Url::toRoute('/verifikator/verifikasi-info-kepengusahaan/index'); ?>"><i class="fa fa-user"></i> Info Kepengusahaan</a></li>
    <li><a href="<?= Url::toRoute('/verifikator/verifikasi-permohonan-rekomendasi/index'); ?>"><i class="fa fa-archive"></i> Permohonan Rekomendasi</a></li>
  </ul>
</div>

<div class="menu_section">
  <h3>Cek Perusahaan & Kendaraan</h3>
  <ul class="nav side-menu">
    <li><a href="<?= Url::toRoute('/cari-perusahaan/index'); ?>"><i class="fa fa-building"></i> Cek Perusahaan</a></li>
    <li><a href="<?= Url::toRoute('/cari-kendaraan/index'); ?>"><i class="fa fa-bus"></i> Cek Kendaraan</a></li>
  </ul>
</div>

backend/views/layoutsbak/tpl_left.php
<?php

use yii\helpers\Url;
use common\models\User;
use common\models\UserRole;
?>

<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="<?= Url::toRoute('/site/index'); ?>" class="site_title">
        <i class="fa fa-car"></i> <span><?= Yii::$app->name; ?></span>
      </a>
      <?php /*
      <a href="<?= \yii\helpers\Url::toRoute(['site/dashboard']);?>">
        <img src="<?= Yii::$app->getUrlManager()->getBaseUrl();?>/img/logo.png" alt="" title="" style="height:55px; padding-top:20px"/>
      </a>
      */ ?>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <img src="<?= $baseTheme; ?>/images/avatar.png" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><?php if (!Yii::$app->user->isGuest) {
              echo ucwords(Yii::$app->user->identity->username);
            } ?></h2>
        <p><?php if (!Yii::$app->user->isGuest) {
              echo ucwords(UserRole::findOne(User::findOne(Yii::$app->user->identity->id)->user_role_id)->role);
            } ?></p>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <?php if (!Yii::$app->user->isGuest && User::findOne(Yii::$app->user->identity->id)->user_role_id == 1) : ?>
        <?= $this->render('_menu_administrator'); ?>
      <?php elseif (!Yii::$app->user->isGuest && User::findOne(Yii::$app->user->identity->id)->user_role_id == 3 || User::findOne(Yii::$app->user->identity->id)->user_role_id == 5 || User::findOne(Yii::$app->user->identity->id)->user_role_id == 6 || User::findOne(Yii::$app->user->identity->id)->user_role_id == 7 || User::findOne(Yii::$app->user->identity->id)->user_role_id == 9) : ?>
        <?= $this->render('_menu_approval'); ?>
      <?php elseif (!Yii::$app->user->isGuest && User::findOne(Yii::$app->user->identity->id)->user_role_id == 4) : ?>
        <?= $this->render('_menu_jr'); ?>
      <?php elseif (!Yii::$app->user->isGuest && User::findOne(Yii::$app->user->identity->id)->user_role_id == 8) : ?>
        <?= $this->render('_menu_cetak') ?>
      <?php endif; ?>
    </div>
    <!-- /sidebar menu -->
  </div>
</div>