frontend/controllers/PerusahaanController.php
<?php

namespace frontend\controllers;

use backend\modules\master\models\JenisDokumenPerusahaanSearch;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use common\models\perusahaan\Perusahaan;
use common\models\ActivityLog;
use common\models\perusahaan\PerusahaanDokumen;
use frontend\models\perusahaan\PerusahaanDomisiliSearch;
use frontend\models\perusahaan\PerusahaanPemegangSahamSearch;
use frontend\models\perusahaan\PerusahaanPengurusSearch;
use frontend\models\perusahaan\SkPerusahaanSearch;

/**
 * Perusahaan Controller
 */
class PerusahaanController extends Controller
{

  /**
   * {@inheritdoc}
   */
  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'rules' => [
          [
            'actions' => ['profil-perusahaan', 'sunting-data', 'history-verifikasi'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }

  public function beforeAction($action)
  {
    $this->layout = '/dashboard/main';
    return parent::beforeAction($action);
  }

  /**
   * Page Profile Perusahaan
   * @var $model refers to Perusahaan Model
   * @var perusahaan_id
   */
  public function actionProfilPerusahaan()
  {
    // ActivityLog::insertLog("view", "", "Menampilkan Profil Perusahaan");
    $perusahaan_id = User::findOne(Yii::$app->user->identity->id);
    if ($perusahaan_id !== NULL) {
      $model = Perusahaan::find()->where(['is_delete' => 0, 'user_id' => $perusahaan_id->id, 'status' => 1])->one();

      // data domisili
      $searchDomisili = new PerusahaanDomisiliSearch();
      $dataDomisili = $searchDomisili->search(Yii::$app->request->queryParams);
      $dataDomisili->query->andWhere('perusahaan_id=' . $model->id);

      // data pengurus
      $searchPengurus = new PerusahaanPengurusSearch();
      $dataPengurus = $searchPengurus->search(Yii::$app->request->queryParams);
      $dataPengurus->query->andWhere('perusahaan_id=' . $model->id);

      // data pemegang saham
      $searchPemegangSaham = new PerusahaanPemegangSahamSearch();
      $dataPemegangSaham = $searchPemegangSaham->search(Yii::$app->request->queryParams);
      $dataPemegangSaham->query->andWhere('perusahaan_id=' . $model->id);

      // dokumen perusahaan
      $searchDokumen = new JenisDokumenPerusahaanSearch();
      $dataDokumen = $searchDokumen->search(Yii::$app->request->queryParams);
      $dataDokumen->query->andWhere('is_active=1');

      //sk perusahaan
      $searchSk = new SkPerusahaanSearch();
      $dataSk = $searchSk->search(Yii::$app->request->queryParams);
      $dataSk->query->andWhere('is_active=1')->andWhere(['perusahaan_id' => $model->id]);

      // file npwp perusahaan
      $perusahaanDok = PerusahaanDokumen::find()->where(['is_delete' => 0, 'perusahaan_id' => $model->id, 'jenis_dokumen_perusahaan_id' => 2])->one();

      return $this->render('profile-perusahaan', [
        'model' => $model,
        'searchDomisili' => $searchDomisili,
        'dataDomisili' => $dataDomisili,
        'searchPengurus' => $searchPengurus,
        'dataPengurus' => $dataPengurus,
        'searchPemegangSaham' => $searchPemegangSaham,
        'dataPemegangSaham' => $dataPemegangSaham,
        'searchDokumen' => $searchDokumen,
        'dataDokumen' => $dataDokumen,
        'perusahaanDok' => $perusahaanDok,
        'dataSk' => $dataSk,
        'searchSk' => $searchSk,
      ]);
    }
  }

  /**
   * Sunting Data Profile Perusahaan
   * @var $model refers to Perusahaan Model
   * @param $id = id perusahaan
   */
  public function actionSuntingData($id)
  {
    $model = Perusahaan::findOne($id);
    $user = User::findOne($model->user_id);
    $perusahaanDok = new PerusahaanDokumen();
    $perusahaanDok->scenario = "create";
    $oldFileNpwp = "";
    if (PerusahaanDokumen::find()->where(['is_delete' => 0, 'perusahaan_id' => $id, 'jenis_dokumen_perusahaan_id' => 2])->one() !== NULL) {
      $perusahaanDok = PerusahaanDokumen::find()->where(['is_delete' => 0, 'perusahaan_id' => $id, 'jenis_dokumen_perusahaan_id' => 2])->one();
      $oldFileNpwp = $perusahaanDok->filename;
    }

    if ($model->load(Yii::$app->request->post()) && $perusahaanDok->load(Yii::$app->request->post())) {
      $dokumen = UploadedFile::getInstance($perusahaanDok, 'filename');
      $directory = Yii::getAlias('@uploads/perusahaan/' . $id . '/legalitas/');
      if ($model->validate()) {
        $model->save();
        $user->email = $model->email;
        $user->username = $model->email;
        $user->save();
        $perusahaanDok->perusahaan_id = $id;
        $perusahaanDok->nama_dokumen = "NPWP Perusahaan";
        $perusahaanDok->no_dokumen = $model->npwp;
        $perusahaanDok->jenis_dokumen_perusahaan_id = 2; // id dari jenis dokumen npwp

        if (!is_dir($directory)) {
          FileHelper::createDirectory($directory);
        }

        if (!empty($dokumen)) {
          $uid = uniqid(time(), true);
          $fileName = $uid . '_dokumen_perusahaan_npwp' . '.' . $dokumen->extension;
          $filePath = $directory . $fileName;

          if ($dokumen->saveAs($filePath)) {
            $perusahaanDok->filename = $fileName;

            if ($perusahaanDok->save(false)) {
              Yii::$app->session->setFlash('success', 'Data berhasil disimpan');
              return $this->redirect(['perusahaan/profil-perusahaan']);
            } else {
              Yii::$app->session->setFlash('danger', 'Data Gagal disimpan');
              return $this->redirect(['perusahaan/profil-perusahaan']);
            }
          }
        } else {
          $perusahaanDok->filename = $oldFileNpwp;
          $perusahaanDok->save();
        }


        Yii::$app->session->setFlash('success', 'Data berhasil disimpan');
        return $this->redirect(['perusahaan/profil-perusahaan']);
      } else {
        $model->errors !== NULL ? Yii::$app->session->setFlash('danger', 'Gagal Menyimpan perubahan, ' . $model->errors['email'][0]) : Yii::$app->session->setFlash('danger', 'Gagal Menyimpan perubahan');
        return $this->redirect(['perusahaan/profil-perusahaan']);
      }
    } elseif (Yii::$app->request->isAjax) {
      return $this->renderAjax('_formSuntingData', [
        'model' => $model,
        'perusahaanDok' => $perusahaanDok,
      ]);
    }
  }

  /**
   * Fungsi untuk menampilkan history Verifikasi
   * mengambil data perusahaan dengan user_id karena kalo dengan perusahaan id data perusahaan yang sebelumnya tidak akan muncul
   * @param int $id = user_id
   */
  public function actionHistoryVerifikasi($id)
  {
    $decoded_id = base64_decode($id) / 2;
    $perusahaan = Perusahaan::find()->where(['is_delete' => 0, 'user_id' => $decoded_id])->all();
    if ($perusahaan !== NULL) {
      return $this->renderAjax('_history_verifikasi', [
        'perusahaan' => $perusahaan,
      ]);
    } else {
      return "Empty";
    }
  }
}

frontend/controllers/RegulasiController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\master\Regulasi;
use frontend\models\master\RegulasiSearch;

/**
 * Regulasi Controller, controller ini hanya menampilkan data Regulasi Perizinan
 */
class RegulasiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'view', 'download', 'preview-dok'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->layout = '/dashboard/main';
        return parent::beforeAction($action);
    }

    /**
     * Lists all Regulasi models.
     * @param jenis_layanan_id
     * @return mixed
     */
    public function actionIndex($jenisLayananId)
    {
//        ActivityLog::insertLog("View", "", "Menampilkan Daftar Regulasi");
        $searchModel = new RegulasiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['jenis_layanan_id' => $jenisLayananId]);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'jenisLayananId' => $jenisLayananId
        ]);
    }

    /**
     * Displays a single Regulasi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Download dokumen regulasi.
     * @param integer $path
     * @return file
     */
    public function actionDownload($path, $file)
    {
        $path = (explode('/', $path));
        $result = array_slice($path, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        if (file_exists($fullpath)) {
            return Yii::$app->response->sendFile($fullpath);
        } else {
            return 'File Not Found';
        }
    }

    /**
     * Preview dokumen regulasi.
     * @param integer $path
     * @return file
     */
    public function actionPreviewDok($path, $file)
    {
        $array = (explode('/', $path));
        $result = array_slice($array, 5);
        $fullpath = Yii::getAlias('@uploads/') . implode("/", $result) . $file;

        return $this->renderAjax('preview-dok', [
            'path' => $path,
            'file' => $file,
            'fullpath' => $fullpath,
        ]);
    }

    /**
     * Finds the Regulasi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Regulasi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Regulasi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/SkPerusahaanController.php
<?php

namespace frontend\controllers;

use common\models\perusahaan\Perusahaan;
use Yii;
use common\models\perusahaan\SkPerusahaan;
use common\models\perusahaan\SkPerusahaanSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * SkPerusahaanController implements the CRUD actions for SkPerusahaan model.
 */
class SkPerusahaanController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SkPerusahaan models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SkPerusahaanSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SkPerusahaan model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $perusahaan = Perusahaan::find()->where(['id' => $model->perusahaan_id])->one();
        return $this->renderAjax('view', [
            'perusahaan' => $perusahaan,
            'model' => $model,
        ]);
    }

    /**
     * Creates a new SkPerusahaan model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($perusahaan_id)
    {
        $this->layout = 'dashboard/main';
        $model = new SkPerusahaan();
        $model->scenario = "create";

        if ($model->load(Yii::$app->request->post())) {
            $dokSK = UploadedFile::getInstance($model, 'file_sk');
            $directory = Yii::getAlias('@uploads/perusahaan/' . $perusahaan_id . '/legalitas/');

            if (!is_dir($directory)) {
                FileHelper::createDirectory($directory);
            }

            $uid = uniqid(time(), true);

            if (!empty($dokSK)) {
                $fileSK = $uid . '_sk' . '.' . $dokSK->extension;
                $filePathSK = $directory . $fileSK;

                if ($dokSK->saveAs($filePathSK)) {
                    $model->file_sk = $fileSK;
                    $perusahaan = Perusahaan::find()->where(['id' => $perusahaan_id])->one();
                    $perusahaan->jenis_perusahaan = 1; //set jenis perusahaan menjadi perusahaan lama
                    $perusahaan->save();
                    if ($model->save()) {
                        Yii::$app->session->setFlash('success', 'Data berhasil disimpan');
                        return $this->redirect(['perusahaan/profil-perusahaan']);
                    }
                }
            }
        }

        return $this->renderAjax('_form', [
            'perusahaan_id' => $perusahaan_id,
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing SkPerusahaan model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id, $perusahaan_id)
    {
        $model = $this->findModel($id);
        $oldSk = $model->file_sk;
        if ($model->load(Yii::$app->request->post())) {
            $dokSk = UploadedFile::getInstance($model, 'file_sk');
            $directory = Yii::getAlias('@uploads/perusahaan/' . $perusahaan_id . '/legalitas/');
            if (!is_dir($directory)) {
                FileHelper::createDirectory($directory);
            }

            $uid = uniqid(time(), true);

            if (!empty($dokSk)) {
                $fileSk = $uid . '_sk' . '.' . $dokSk->extension;
                $filePathSk = $directory . $fileSk;

                if ($dokSk->saveAs($filePathSk)) {
                    $model->file_sk = $fileSk;
                }
            } else {
                $model->file_sk = $oldSk;
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Data berhasil disimpan');
                return $this->redirect(['perusahaan/profil-perusahaan']);
            }
        }

        return $this->renderAjax('_form', [
            'perusahaan_id' => $perusahaan_id,
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SkPerusahaan model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->is_delete = 1;

        return $this->redirect(['perusahaan/profile-perusahaan']);
    }

    /**
     * Finds the SkPerusahaan model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SkPerusahaan the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SkPerusahaan::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/perusahaan/_data_pemegang_saham.php
<?php

use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\helpers\Html;
?>
<?php Pjax::begin(['id' => 'data-pemegang-saham']); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataPemegangSaham,
        'filterModel' => $searchPemegangSaham,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // 'perusahaan_id',
            'nik',
            [
                'attribute' => 'file_ktp',
                'format' => 'RAW',
                'value' => function ($data) {
                    $button = "";
                    if ($data->file_ktp !== NULL) {
                        $button = Html::button('<i class="fa fa-file-pdf-o"></i>', ['value' => Url::toRoute(['regulasi/preview-dok', 'path' => Yii::$app->urlManagerUpload->baseUrl . '/perusahaan/' . $data->perusahaan_id . '/legalitas/', 'file' => $data->file_ktp]), 'title' => 'Preview Dokumen', 'class' => 'showModalButton btn btn-primary btn-sm']);
                    }

                    return $button;
                },
                'contentOptions' => ['style' => 'width: 50px;font-align: center;'],
            ],
            'npwp',
            [
                'attribute' => 'file_npwp',
                'format' => 'RAW',
                'value' => function ($data) {
                    $button = "";
                    if ($data->file_npwp !== NULL) {
                        $button = Html::button('<i class="fa fa-file-pdf-o"></i>', ['value' => Url::toRoute(['regulasi/preview-dok', 'path' => Yii::$app->urlManagerUpload->baseUrl . '/perusahaan/' . $data->perusahaan_id . '/legalitas/', 'file' => $data->file_npwp]), 'title' => 'Preview Dokumen', 'class' => 'showModalButton btn btn-primary btn-sm']);
                    }

                    return $button;
                },
                'contentOptions' => ['style' => 'width: 50px;font-align: center;'],
            ],
            'nama_lengkap',
            [
                'attribute' => 'persentase',
                'value' => function ($data) {
                    return $data->persentase . "%";
                }
            ],
            'keterangan:ntext',
            //'created_at',
            //'updated_at',
            //'created_by',
            //'updated_by',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Aksi',
                'template' => '{view}{update}{delete}',
                'contentOptions' => ['width' => "120px"],
                'buttons' => [
                    'view' => function ($url, $model) use ($perusahaan) {
                        return $button = Html::button('<i class="fa fa-eye"></i>', ['value' => Url::toRoute(['perusahaan-pemegang-saham/view', 'id' => $model->id]), 'title' => 'Detail View Pemegang Saham', 'class' => 'showModalButton btn btn-primary btn-xs']);
                    },
                    'update' => function ($url, $model) use ($perusahaan) {
                        $button = "";
                        if ($perusahaan->is_verified == 0 || $perusahaan->is_verified == 2 || $perusahaan->is_verified == 4) {
                            $button = Html::button('<i class="fa fa-edit"></i>', ['value' => Url::toRoute(['perusahaan-pemegang-saham/update', 'id' => $model->id]), 'title' => 'Update', 'class' => 'showModalButton btn btn-warning btn-xs', 'style' => ['margin-left' => '5px;']]);
                        }

                        return $button;
                    },
                    'delete' => function ($url, $model) use ($perusahaan) {
                        $button = "";
                        if ($perusahaan->is_verified == 0 || $perusahaan->is_verified == 2 || $perusahaan->is_verified == 4) {
                            $button = Html::a('<i class="fa fa-trash"></i>', ['perusahaan-pemegang-saham/delete', 'id' => $model->id], [
                                'class' => 'btn btn-danger btn-xs',
                                'style' => ['margin-left' => '5px'],
                                'data' => [
                                    'confirm' => 'Are you sure you want to delete this item?',
                                    'method' => 'post',
                                ],
                            ]);
                        }
                        return $button;
                    }
                ],
            ],
        ],
    ]); ?>

<?php Pjax::end(); ?>
<?php $this->registerJs('
jQuery(document).ready(function($){
    $(document).ready(function () {
        $("body").on("beforeSubmit", "form#perusahaan-pemegang-saham-form", function () {
            var form = $(this);
            var data = new FormData( this );
            // return false if form still have some validation errors
            if (form.find(".has-error").length)
            {
                return false;
            }
            // submit form
            $.ajax({
                url         : form.attr("action"),
                data        : data,
                type        : form.attr("method"),
                cache       : false,
                contentType : false,
                processData : false,
                beforeSend  : function(){
                    $("#btn-submit").prop("disabled", true);
                    $("#btn-close").prop("disabled", true);
                },
                success: function (response)
                {
                    $("#modal").modal("toggle");
                },
                error  : function ()
                {
                    console.log("internal server error");
                }
            });
            return false;
            });
    });
});
'); ?>

frontend/views/perusahaan/_data_perusahaan.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\helpers\Url;

?>
<?php Pjax::begin(['id' => 'data-perusahaan']) ?>
<table class="table table-striped">
    <tr>
        <td style="width: 25%;font-weight: bold;">Status Perusahaan</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->checkStatus($model->is_verified); ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">Kode Perusahaan</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->kode_perusahaan == NULL ? "-" : $model->kode_perusahaan; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">Jenis Badan Usaha</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->jenisBadanUsaha == NULL ? "-" : $model->jenisBadanUsaha->jenis_badan_usaha; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">Nama Perusahaan</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->nama_perusahaan; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">NPWP Perusahaan</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->npwp; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">File NPWP</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $perusahaanDok !== NULL ? Html::button('<i class="fa fa-file-pdf-o"></i>', ['value' => Url::toRoute(['regulasi/preview-dok', 'path' => Yii::$app->urlManagerUpload->baseUrl . '/perusahaan/' . $model->id . '/legalitas/', 'file' => $perusahaanDok->filename]), 'title' => 'Preview Dokumen', 'class' => 'showModalButton btn btn-primary btn-sm']) : "dokumen tidak ada"; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">Email</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->email; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">No. HP</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->hp; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">Website</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= $model->website == NULL ? "-" : $model->website; ?></td>
    </tr>
    <tr>
        <td style="width: 25%;font-weight: bold;">History Verifikasi</td>
        <td style="width: 7%;font-weight: bold;">:</td>
        <td><?= Html::button('<i class="fa fa-history"></i> History Verifikasi', ['value' => Url::toRoute(['perusahaan/history-verifikasi', 'id' => base64_encode($model->user_id * 2)]), 'title' => 'History Verifikasi', 'class' => 'showModalButton btn btn-primary btn-xs']) ?></td>
    </tr>
</table>
<?php Pjax::end() ?>
<?php $this->registerJs('
jQuery(document).ready(function($){
        $(document).ready(function () {
            $("body").on("beforeSubmit", "form#sunting-data", function () {
                var form = $(this);
                var data = new FormData( this );
                // return false if form still have some validation errors
                if (form.find(".has-error").length)
                {
                    return false;
                }
                // submit form
                $.ajax({
                    url         : form.attr("action"),
                    data        : data,
                    type        : form.attr("method"),
                    cache       : false,
                    contentType : false,
                    processData : false,
                    success: function (response)
                    {
                        $("#modal").modal("toggle");
                        console.log(response === "true");
                        if(response === "true"){
                            $.pjax.reload({container:"#data-perusahaan", async: false}); //for pjax update
                            Swal.fire(
                                  "Berhasil!",
                                  "Perubahan Berhasil Disimpan.",
                                  "success"
                                )
                        }else{
                            $.pjax.reload({container:"#data-perusahaan", async: false}); //for pjax update

                            Swal.fire(
                                  "Gagal!",
                                  "Perubahan Gagal Disimpan.",
                                  "danger"
                                )
                        }
                    },
                    error  : function ()
                    {
                        console.log("internal server error");
                    }
                });
                return false;
                });
        });
    });
'); ?>